[app]
name = "WiFi Manager"
category = "Apps"

[entry]
class = "WiFiManager"

[metadata]
author = "sam"
license = "MIT"
url = "https://github.com/sammachin/wifi-manager"
description = "Store, manage, activate and share Wi-Fi profiles on your badge."
version = "1.0.0"
